In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/data.csv')

In [ ]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

###DATA CLEANING

In [ ]:
#Fillna
#dropna
df.dropna(how='any', inplace=True)

In [ ]:
len(df)

569

In [ ]:
#Checking y variable
df.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [ ]:
#checking precentage
df.diagnosis.value_counts()/len(df)*100

diagnosis
B    62.741652
M    37.258348
Name: count, dtype: float64

#Splitting the Data

In [ ]:
X = df.drop(["id","diagnosis"], axis=1)


In [ ]:
y = df.diagnosis.values

#TRAINING AND TEST SPLIT

In [ ]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
len(X_train)

426

In [ ]:
len(X_test)

143

#FEATURE SCALING

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [ ]:
X_train_sc

array([[ 0.99146487,  0.96836233,  1.12125865, ...,  1.33499328,
        -0.93333687,  2.05977398],
       [ 1.08984588,  0.19789546,  0.92504676, ...,  0.08431231,
         3.12764252, -1.21025725],
       [-0.05980655, -0.51687502, -0.02494582, ...,  0.80757911,
         1.15772923,  1.17944252],
       ...,
       [-1.34297608, -1.22004207, -1.29214762, ..., -0.62322459,
         1.2379733 ,  0.32151949],
       [-0.17786377,  0.56224274, -0.22034016, ..., -0.0282644 ,
         0.15703845, -0.65804933],
       [ 0.82843347,  1.11920674,  0.86781829, ...,  1.10521342,
         1.00038791,  0.05475238]])

#MODEL BUILDING

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

#intiate the classifier
model_knn = KNeighborsClassifier()

#Passing the data to Classifier
model_knn.fit(X_train_sc, Y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = model_knn.predict(X_test_sc)

In [ ]:
y_pred_knn

array(['B', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B',
       'M', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'M', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B'],
      dtype=object)

In [ ]:
Y_test

array(['B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B',
       'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B',
       'M', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'M', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B'],
      dtype=object)

In [ ]:
 #Classification metrics to check how to model behaves

 from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
 print(np.round(confusion_matrix(Y_test, y_pred_knn)*100,2))
 print(classification_report(Y_test, y_pred_knn))
 print(np.round(accuracy_score(Y_test, y_pred_knn)*100,2))

[[8400  200]
 [ 200 5500]]
              precision    recall  f1-score   support

           B       0.98      0.98      0.98        86
           M       0.96      0.96      0.96        57

    accuracy                           0.97       143
   macro avg       0.97      0.97      0.97       143
weighted avg       0.97      0.97      0.97       143

97.2


#Checking the New Data

In [ ]:
new_data =[[12,21.82,86.6,519.8,0.1273,0.1932,0.1299,0.09353,0.235,0.08389,0.3063,1.002,2.406,24.32,0.005731,0.03502,0.03553,0.01226,0.02143,
0.003749,15.49,30.73,106.2,739.3,0.1703,0.5401,0.539,0.206,0.4278,0.1072]]


In [ ]:
new_data_sc = sc.transform(new_data)

In [ ]:
new_data_sc

array([[-0.58263137,  0.61793914, -0.20317162, -0.36930646,  2.19765755,
         1.72218249,  0.53241404,  1.20575453,  1.99755462,  2.88002558,
        -0.34008808, -0.39452835, -0.21834588, -0.32597913, -0.44546926,
         0.48915349,  0.08834528,  0.04660072,  0.06663919, -0.04092213,
        -0.13876096,  0.84959846, -0.00852798, -0.22885873,  1.68877648,
         1.79847113,  1.26738925,  1.43369066,  2.17730096,  1.24880197]])

In [ ]:
y_pred_single = model_knn.predict(new_data_sc)
y_pred_single

array(['M'], dtype=object)

In [ ]:
new_data_1 = [[13,21.82,87.5,519.8,0.1273,0.1932,0.1859,0.09353,0.235,0.07389,0.3063,1.002,2.406,24.32,0.005731,0.03502,0.03553,0.01226,0.02143,
0.003749,15.49,30.73,106.2,739.3,0.1703,0.5401,0.539,0.206,0.4378,0.1072]]

In [ ]:
new_data_sc1 = sc.transform(new_data_1)
y_pred_single1 = model_knn.predict(new_data_sc1)
y_pred_single1

array(['M'], dtype=object)